/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cbtapp;

import javax.swing.JFrame;

/**
 *
 * @author d03x
 */
public class EntryApp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntryApp.class.getName());

    /**
     * Creates new form EntryApp
     */
    public EntryApp() {
        initComponents();
        setLocationRelativeTo(null);
        this.pendaftaran3.setVisible(false);
        this.dataSiswa2.setVisible(false);

        setExtendedState(JFrame.MAXIMIZED_BOTH); // Fullscreen + centered
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendaftaran1 = new cbtapp.component.Pendaftaran();
        Header = new javax.swing.JPanel();
        Close = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LabelQ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        BerandaMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BerandaMenu1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BerandaMenu2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BerandaMenu4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BerandaMenu5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pendaftaran3 = new cbtapp.component.Pendaftaran();
        dataSiswa2 = new cbtapp.component.DataSiswa();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(102, 102, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        Header.setPreferredSize(new java.awt.Dimension(884, 40));

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/x2.png"))); // NOI18N

        javax.swing.GroupLayout CloseLayout = new javax.swing.GroupLayout(Close);
        Close.setLayout(CloseLayout);
        CloseLayout.setHorizontalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CloseLayout.setVerticalGroup(
            CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        LabelQ.setBackground(new java.awt.Color(0, 102, 255));
        LabelQ.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        LabelQ.setForeground(new java.awt.Color(0, 102, 255));
        LabelQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelQ.setText(".::PPDB APP");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1015, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));
        Sidebar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 153, 153))));
        Sidebar.setPreferredSize(new java.awt.Dimension(270, 699));

        BerandaMenu.setBackground(new java.awt.Color(204, 204, 204));
        BerandaMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Beranda");
        BerandaMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 38));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lucide--home.png"))); // NOI18N
        BerandaMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 44, 38));

        BerandaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        BerandaMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BerandaMenu1MouseClicked(evt);
            }
        });
        BerandaMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Pendaftaran");
        BerandaMenu1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 38));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9165490_file_form_document_icon.png"))); // NOI18N
        BerandaMenu1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 44, 38));

        BerandaMenu2.setBackground(new java.awt.Color(255, 255, 255));
        BerandaMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Cetak Kartu");
        BerandaMenu2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 38));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/39263_print_printer_icon.png"))); // NOI18N
        BerandaMenu2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 44, 38));

        BerandaMenu4.setBackground(new java.awt.Color(255, 255, 255));
        BerandaMenu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Laporan");
        BerandaMenu4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 38));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/solar--pie-chart-bold-duotone.png"))); // NOI18N
        BerandaMenu4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 44, 38));

        BerandaMenu5.setBackground(new java.awt.Color(255, 255, 255));
        BerandaMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BerandaMenu5MouseClicked(evt);
            }
        });
        BerandaMenu5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Data Siswa");
        BerandaMenu5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 38));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/material-symbols--docs.png"))); // NOI18N
        BerandaMenu5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 44, 38));

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BerandaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BerandaMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BerandaMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BerandaMenu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BerandaMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addComponent(BerandaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BerandaMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BerandaMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BerandaMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BerandaMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        getContentPane().add(Sidebar, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pendaftaran3, java.awt.BorderLayout.CENTER);
        jPanel1.add(dataSiswa2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/lucide--cog.png"))); // NOI18N
        jMenu1.setText("Pengaturan");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informasi");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void BerandaMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaMenu1MouseClicked
        this.showPanel(pendaftaran3, "Form pendaftaran");

    }//GEN-LAST:event_BerandaMenu1MouseClicked

    private void BerandaMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaMenu5MouseClicked
        this.showPanel(dataSiswa2, "Data pendaftaran");

    }//GEN-LAST:event_BerandaMenu5MouseClicked
    public void setTitle(String text) {
        this.LabelQ.setText(text);
    }

    public void showPanel(javax.swing.JPanel panel, String title) {
        if (currentPanel != null) {
            currentPanel.setVisible(false);
            lastPanel = currentPanel; // simpan sebelumnya
        }

        currentPanel = panel;
        currentPanel.setVisible(true);
        setTitle(title);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EntryApp().setVisible(true));
    }
    private javax.swing.JPanel currentPanel = null;
    private javax.swing.JPanel lastPanel = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BerandaMenu;
    private javax.swing.JPanel BerandaMenu1;
    private javax.swing.JPanel BerandaMenu2;
    private javax.swing.JPanel BerandaMenu4;
    private javax.swing.JPanel BerandaMenu5;
    private javax.swing.JPanel Close;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabelQ;
    private javax.swing.JPanel Sidebar;
    private cbtapp.component.DataSiswa dataSiswa2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private cbtapp.component.Pendaftaran pendaftaran1;
    private cbtapp.component.Pendaftaran pendaftaran3;
    // End of variables declaration//GEN-END:variables
}
