/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cbtapp.component;

import java.sql.*;
import cbtapp.utils.DB;
import javax.swing.*;
import javax.swing.JOptionPane;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author d03x
 */
public class Pendaftaran extends javax.swing.JPanel {

    public void loadSekolah() {
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(new Array[]{});

        try {
            String sql = "SELECT npsn, nama FROM sekolah_asal ORDER BY nama";
            PreparedStatement ps = DB.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int npsn = rs.getInt("npsn");
                String nama = rs.getString("nama");
                model.addElement(nama + " - " + npsn);
            }

            inputAsalSekolah.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data sekolah: " + e.getMessage());
        }
    }

    public Pendaftaran() {
        initComponents();

        this.loadSekolah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputEmail = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        InputNISN = new javax.swing.JTextField();
        inputHP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        InputDate = new com.toedter.calendar.JDateChooser();
        inputAsalSekolah = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputNoWa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatAsalSekolah = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        alamatSekolahAsal = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        ButtonDaftar = new javax.swing.JButton();
        InputTempatLahir1 = new javax.swing.JTextField();
        btnUploadFoto = new javax.swing.JButton();
        previewFoto = new javax.swing.JLabel();

        inputEmail.setColumns(20);
        inputEmail.setRows(5);
        jScrollPane1.setViewportView(inputEmail);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Tanggal Lahir");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 220, 20));
        add(InputNISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 450, -1));

        inputHP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                inputHPComponentResized(evt);
            }
        });
        add(inputHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 220, -1));

        jLabel5.setText("Nisn");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, -1));

        jLabel6.setText("Nama Lengkap");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 220, 20));
        add(InputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 450, -1));

        jLabel7.setText("Asal Sekolah");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, -1));
        add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 450, -1));

        jLabel8.setText("Tempat Lahir");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 20));
        add(InputDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 220, -1));

        inputAsalSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAsalSekolahActionPerformed(evt);
            }
        });
        add(inputAsalSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 450, 30));

        jLabel9.setText("Nomor Whatsap");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 210, -1));

        jLabel10.setText("Email");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, -1));

        jLabel11.setText("Alamat Sekarang");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 220, -1));
        add(inputNoWa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 220, -1));

        jLabel12.setText("No HP");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 220, -1));

        alamatAsalSekolah.setColumns(20);
        alamatAsalSekolah.setRows(5);
        jScrollPane3.setViewportView(alamatAsalSekolah);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 450, -1));

        alamatSekolahAsal.setColumns(20);
        alamatSekolahAsal.setRows(5);
        jScrollPane4.setViewportView(alamatSekolahAsal);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 450, 80));

        jLabel13.setText("Alamat Asal Sekolah");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 220, -1));

        ButtonDaftar.setText("Daftar");
        ButtonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDaftarActionPerformed(evt);
            }
        });
        add(ButtonDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 450, 40));
        add(InputTempatLahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, -1));

        btnUploadFoto.setText("Upload Foto");
        btnUploadFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFotoActionPerformed(evt);
            }
        });
        add(btnUploadFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 110, -1));

        previewFoto.setBackground(new java.awt.Color(204, 204, 204));
        previewFoto.setForeground(new java.awt.Color(153, 153, 153));
        previewFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previewFoto.setText("Preview");
        previewFoto.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        add(previewFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 110, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void inputHPComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_inputHPComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHPComponentResized

    private void inputAsalSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAsalSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAsalSekolahActionPerformed

    private void ButtonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDaftarActionPerformed
        if (!this.validateForm()) {
            return;
        }
        try {
            String sql = "INSERT INTO peserta (nisn, nama_lengkap, tempat_lahir, tanggal_lahir, email, npsn_sekolah_asal, alamat_sekolah_asal, no_hp, no_wa, alamat,foto) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";

            PreparedStatement ps = DB.getConnection().prepareStatement(sql);

            ps.setString(1, InputNISN.getText());
            ps.setString(2, InputNama.getText());
            ps.setString(3, InputTempatLahir1.getText());

            // ambil tanggal dari JDateChooser
            java.util.Date utilDate = InputDate.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            ps.setDate(4, sqlDate);

            ps.setString(5, Email.getText());

            // ambil NPSN dari combobox: "SMP X - 123456"
            String selectedItem = (String) inputAsalSekolah.getSelectedItem();
            String npsn = selectedItem.split(" - ")[1]; // ambil bagian setelah " - "
            ps.setString(6, npsn);

            ps.setString(7, alamatSekolahAsal.getText());
            ps.setString(8, inputHP.getText());
            ps.setString(9, inputNoWa.getText());
            ps.setString(10, alamatAsalSekolah.getText());

            //upload file handler
            String fotoFileName = null;
            if (selectedFotoFile != null) {
                fotoFileName = System.currentTimeMillis() + "_" + selectedFotoFile.getName();
                File dest = new File("uploads/" + fotoFileName);
                try {
                    java.nio.file.Files.copy(selectedFotoFile.toPath(), dest.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan file foto: " + ex.getMessage());
                    return;
                }
            }
            ps.setString(11, fotoFileName);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            this.resetForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan: " + ex.getMessage());
        }
    }//GEN-LAST:event_ButtonDaftarActionPerformed
    private void uploadFoto() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih Foto");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Gambar", "jpg", "png", "jpeg"));

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFotoFile = fileChooser.getSelectedFile();

            // Preview
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(selectedFotoFile.getAbsolutePath())
                    .getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH));
            previewFoto.setIcon(imageIcon);
        }
    }

    private void btnUploadFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFotoActionPerformed

        uploadFoto();

    }//GEN-LAST:event_btnUploadFotoActionPerformed
    private boolean validateForm() {
        if (InputNISN.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NISN wajib diisi!");
            InputNISN.requestFocus();
            return false;
        }

        if (InputNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama lengkap wajib diisi!");
            InputNama.requestFocus();
            return false;
        }

        if (InputTempatLahir1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tempat lahir wajib diisi!");
            InputTempatLahir1.requestFocus();
            return false;
        }

        if (InputDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal lahir wajib diisi!");
            InputDate.requestFocus();
            return false;
        }

        if (Email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email wajib diisi!");
            Email.requestFocus();
            return false;
        }

        if (inputAsalSekolah.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Asal sekolah wajib dipilih!");
            inputAsalSekolah.requestFocus();
            return false;
        }

        if (alamatSekolahAsal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat asal sekolah wajib diisi!");
            alamatSekolahAsal.requestFocus();
            return false;
        }

        if (inputHP.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No HP wajib diisi!");
            inputHP.requestFocus();
            return false;
        }

        if (inputNoWa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No WhatsApp wajib diisi!");
            inputNoWa.requestFocus();
            return false;
        }

        if (alamatAsalSekolah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat sekarang wajib diisi!");
            alamatAsalSekolah.requestFocus();
            return false;
        }

        return true; // Semua valid
    }

    private void resetForm() {
        InputNISN.setText("");
        InputNama.setText("");
        InputTempatLahir1.setText("");
        InputDate.setDate(null);
        Email.setText("");
        inputAsalSekolah.setSelectedIndex(0);
        alamatSekolahAsal.setText("");
        inputHP.setText("");
        inputNoWa.setText("");
        alamatAsalSekolah.setText("");
        previewFoto.setIcon(null);
        selectedFotoFile = null;
    }

    private File selectedFotoFile = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDaftar;
    private javax.swing.JTextField Email;
    private com.toedter.calendar.JDateChooser InputDate;
    private javax.swing.JTextField InputNISN;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTextField InputTempatLahir1;
    private javax.swing.JTextArea alamatAsalSekolah;
    private javax.swing.JTextArea alamatSekolahAsal;
    private javax.swing.JButton btnUploadFoto;
    private javax.swing.JComboBox<String> inputAsalSekolah;
    private javax.swing.JTextArea inputEmail;
    private javax.swing.JTextField inputHP;
    private javax.swing.JTextField inputNoWa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel previewFoto;
    // End of variables declaration//GEN-END:variables
}
